ignore:
  - "documentations/Exo\ 4/price.liquid"
  - "documentations/Exo\ 4/main-cart-items.liquid"
  - "documentations/Exo\ 4/cart-drawer.liquid"
  - "documentations/Exo\ 1/cart-promo.js"
  - "documentations/Exo\ 1/theme.liquid"

MatchingTranslations:
  enabled: false

TemplateLength:
  enabled: false

# Désactive la vérification des filtres
UnknownFilter:
  enabled: false

# Mise en warning des snippets trop imbriqués + syntaxe liquid
NestedSnippet:
  enabled: warning

LiquidTag:
  enabled: warning